var path = require("path");
module.exports = {
  context:__dirname,
  entry:{
    bundle:"./src/index.js"
  },
  output:{
    path:path.resolve(__dirname,"dist"),
    filename:"[name].js"
  },
  module:{
    rules:[{
      exclude:/node_modules/,
      test:/\.scss$/,
      use:["style-loader","css-loader","sass-loader"]
    },{
      test:/\.ttf/,
      exclude:/node_modules/,
      use:{loader:"url-loader"}
    },{
      test:/\.js$/,
      exclude:/node_modules/,
      use:{
        loader:"babel-loader",
        query:{
          presets:["@babel/preset-react"]
        },
      }
    }]
  },
  devtool:"source-map"
}
